name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug directory
        run: |
          echo "Working directory:"
          pwd
          echo "Directory contents:"
          ls -la
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          npm install
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build
        working-directory: ${{ github.workspace }}
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4